name: skrt+
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyter
  - jupyterlab
  - pip
  - python=3.8
  - root
  - pip:
    - ganga
    - -e ../scikit-rt
    - -e ../scikit-rt/examples/import
    - -e ../scikit-rt/examples/innereye
    - -e ../voxtox-skrt
    - -e ../ganga-skrt
    - simpleitk
