name: skrt+
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyter
  - jupyterlab
  - pip
  - python=3.10
  - root
  - pip:
    - ganga==8.6.8
    - -e ../ganga-skrt
    - -e ../scikit-rt
    - -e ../voxtox-skrt
