name: skrt+
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyter
  - jupyterlab
  - pip
  - python=3.10
  - root
  - pip:
    - ganga
    - scikit-rt
    - -e git+https://codeshare.phy.cam.ac.uk/kh296/ganga-skrt#egg=ganga-skrt
    - -e .
